### ISSUE TITLE
insert() method doesn't return the modified list; instead, it modifies the list in place and returns None 

### ISSUE THREAD

**Issue by demohatesrng** [tardis-sn/tardis#2489] opened 2023-12-03 18:07 UTC
insert() method doesn't return the modified list; instead, it modifies the list in place and returns None

in density.py file modify velocity list with 0 inserted at the beginning, and the operations should work just as fine.
its just something i found that we could improve kindly have a look at it please
and feel free to give more solutions if possible
** a simple fix coule be **
at line number 105/106
        velocity.insert(0, 0)
        adjusted_velocity = velocity

**Comment by demohatesrng** [comment] 2023-12-03 18:08
<img width="997" alt="Screenshot 2023-12-03 at 11 38 21 PM" src="https://github.com/tardis-sn/tardis/assets/127432312/57ce1865-256f-4750-8284-de831ffc44e3">

**Comment by ArpBansal** [comment] 2023-12-16 11:03
@demohatesrng So should I create a new method that modifies the list and then return the modified one?

**Comment by mohakmalviya** [comment] 2023-12-21 19:42
hello @demohatesrng the issue is still there?

**Comment by demohatesrng** [comment] 2023-12-29 18:07
> hello @demohatesrng the issue is still there?

hey there, i mean it is what i am suggesting , from my perspective of what i understand the code base, feel free to drop a recommendation , it does work just fine after modifying the velocity to 0

**Comment by andrewfullard** [comment] 2024-01-03 18:26
We are in the process of restructuring large parts of the code, so this issue will likely be addressed in a different way.

**Comment by demohatesrng** [comment] 2024-01-04 11:48
> We are in the process of restructuring large parts of the code, so this issue will likely be addressed in a different way.

I have been looking and understanding on the codebase for quite some time now i may have an idea to solve these minor bugs, Reach out on Some Platform ?

**Comment by atharva-2001** [comment] 2024-01-04 11:52
Gitter is best.
https://gitter.im/tardis-sn/gsoc

**Closed** 2024-02-22 17:39 UTC
Labels: priority - low :snail:, codestyle
