### ISSUE TITLE
Montecarlo Packet Progress bar does not go to 100%

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#2216] opened 2023-02-21 15:36 UTC
**Describe the bug**
When running the montecarlo main loop, the progress bar updates with an approximation for the number of packets completed when run in multithreaded mode.  At the end of the loop, the progress bar is no longer updated so the display never shows it reaching 100%.  

To solve this problem, at the end of the loop another update call to the progress bar should be made to fill out the remaining progress.  

**To Reproduce**
Run a tardis model with >=2 threads

**System**
 - OS:
    - [x] GNU/Linux
    - [x] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by AyushiDaksh** [comment] 2023-02-28 13:39
@Rodot- Are you still working on this? If not, can I pick it up?

**Comment by Rodot-** [comment] 2023-02-28 14:55
I'm not working on this myself so it is definitely up for grabs

**Comment by shreyas3156** [comment] 2023-03-06 18:52
@Rodot- There seems to be a delay of a few seconds (even after the particular cell in the notebook has finished running), after which the packet progress bar does update to 100%. I could reproduce this for **1** <= no. of threads <= **4**.

**Comment by shreyas3156** [comment] 2023-03-09 18:41
Hi @Rodot- I have made a PR that aims to solve this issue. It would be great if you could review it.

**Comment by atharva-2001** [comment] 2023-03-21 12:05
@Rodot- Does PR https://github.com/tardis-sn/tardis/pull/2237 fix this issue?

**Comment by MarkMageeAstro** [comment] 2024-11-15 17:21
Seems to be fixed now

**Closed** 2024-11-15 19:28 UTC
Labels: easy, priority - low :snail:, bug :lady_beetle:, visualization
