### ISSUE TITLE
Missing File/Directory Issue

### ISSUE THREAD

**Issue by MikeFoly** [tardis-sn/tardis#805] opened 2017-11-14 21:02 UTC
I followed the installation instructions in creating a virtual environment through Anaconda and installing the development version of Tardis. When I try to run the example code, however, I receive the error found in the attached text file regarding a missing supernova.yml file. However, when I navigate to that directory (/anaconda/envs/tardis/lib/python2.7/site-packages/tardis/io/schemas), I find that the supernova.yml file is actually there. 

[Error_Returned.txt](https://github.com/tardis-sn/tardis/files/1472502/Error_Returned.txt)

**Comment by wkerzendorf** [comment] 2017-11-14 21:28
@MikeFoly try it now.

**Comment by MikeFoly** [comment] 2017-11-19 04:01
@wkerzendorf Tried reinstalling the development version of Tardis and rerunning, but I still get the same error. Is there anything else I should try? Thanks!

**Comment by wkerzendorf** [comment] 2017-11-24 11:28
@tardis-sn/tardis-core anyone ever encountered this?

**Comment by wkerzendorf** [comment] 2017-11-24 14:50
@MikeFoly I can't reproduce the error. Can you update this issue with your setup? what operating system etc.

**Comment by unoebauer** [comment] 2017-11-27 10:32
@MikeFoly I just checked out the current master version of TARDIS and tried to reproduce your Error but  TARDIS actually works flawlessly on my installation.

**Comment by unoebauer** [comment] 2018-04-05 11:56
Closing - reopen if error persists

**Closed by unoebauer** 2018-04-05 11:56 UTC
