### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#376] opened 2015-08-17 12:26 UTC
Working with the current master branch, I'm failing to build from source:

```
python setup.py build
```

eventually gives up with:

```
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/montecarlo.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/cmontecarlo.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/rpacket.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/test_cmontecarlo.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/test_rpacket.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_isaac.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_mt.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_primitive.o build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_sobol.o -o build/lib.macosx-10.10-x86_64-2.7/tardis/montecarlo/montecarlo.so
duplicate symbol _mt_state in:
    build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/cmontecarlo.o
    build/temp.macosx-10.10-x86_64-2.7/tardis/montecarlo/src/rpacket.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang' failed with exit status 1
```

Looks like a problem with my C compiling? @wkerzendorf @aoifeboyle @orbitfold Anyone know?

**Comment by orbitfold** [comment] 2015-08-17 12:33
Did you do git clean -dfx?

**Comment by ssim** [comment] 2015-08-17 12:34
Hi - no, I'd not done that. But I tried doing it now - still get the same problem.

**Comment by orbitfold** [comment] 2015-08-17 12:37
I know what the problem is. Give me a sec.

**Comment by orbitfold** [comment] 2015-08-17 12:48
Can you try now? If this does not fix it I'll have to look at it once I get back home.

**Comment by ssim** [comment] 2015-08-17 12:51
do I need to pull again now? what do I do different from before?

**Comment by orbitfold** [comment] 2015-08-17 12:51
Nothing, just pull again.

**Comment by ssim** [comment] 2015-08-17 12:53
Ok - so I did a pull and then

```git clean -dfx ```

and this time 

``` python setup.py build```

claims to have worked - yay! Many thanks! What was the issue? Is it something I'll need to worry about again?

Many thanks!

**Comment by orbitfold** [comment] 2015-08-17 12:57
Well the issue was basically that a variable with the same name was declared in two files that were later linked together. I don't understand how did the tests pass...

**Comment by ssim** [comment] 2015-08-17 12:59
Would you say that it's resolved now? Or should we leave this issue open?

**Comment by orbitfold** [comment] 2015-08-17 13:00
Let's leave it open I think.

**Comment by ssim** [comment] 2015-08-17 13:01
OK - will leave it. Can bring it up at the next TARDIS meeting. Thanks for your help!

**Comment by orbitfold** [comment] 2015-08-17 13:03
No problem, glad it worked.

**Comment by unoebauer** [comment] 2015-11-30 10:49
The fundamental problem, which this issue refers to, is still unresolved. It is diagnosed in detail in #390, namely that the C-modules are not recompiled if the corresponding ``*.c``, ``*.h`` (and possibly ``*.pyx``) are changed. This also holds if the compile flags are changed (e.g. activating open-mp or virtual-packet loggin). It seems to be related to the (wrong?) use of astropy's setuphelpers. @chvogl is doing a proper analysis of this problem right now.

**Comment by wkerzendorf** [comment] 2015-11-30 10:50
once @chvogl's analysis is complete we should contact the astropy people to help us with this problem.

**Comment by unoebauer** [comment] 2016-11-18 10:25
Ok - the our MO seems to be to always suggest a ``git clean -ndfx`` followed by ``git clean -dfx``. This seems to have solved (almost?) all such build related problems - this will end up on the documentation.

Closing

**Closed by unoebauer** 2016-11-18 10:25 UTC
Labels: building, priority - high
