### ISSUE TITLE
NLTE not working

### ISSUE THREAD

**Issue by livnehra** [tardis-sn/tardis#777] opened 2017-08-10 18:56 UTC
Hi,

NLTE is not working for me in tardis version 1.5.dev2783.
This occurs for different species and gives at least 2 types of errors.
My setup is standard, using the given kurucz atomic dataset.
Enclosed find Yaml files and results.

[pip_list.txt](https://github.com/tardis-sn/tardis/files/1215999/pip_list.txt)
[tardis_example_nlte.zip](https://github.com/tardis-sn/tardis/files/1215994/tardis_example_nlte.zip)

**Comment by yeganer** [comment] 2017-08-11 11:58
Thanks for the config. So far I found several issues with the current state of the code and I'll work on solving these in the course of next week. Please stay tuned :)

**Comment by yeganer** [comment] 2017-08-16 07:42
@livnehra I looked into the issues and #778 should fix NLTE for now. setup2 runs fine but setup1 has a different error which most likely is related to me not using a database that contains collision data.

**Comment by livnehra** [comment] 2017-08-16 18:32
OK, great!
I'll wait for the merge, rebase and check.

**Comment by yeganer** [comment] 2017-08-17 08:46
It looks like NLTE is working again. I was able to reproduce figure 10 of KerzendorfSim2014:

![nlte_verification](https://user-images.githubusercontent.com/6164110/29403637-2d27c3b0-8339-11e7-8a50-c3c9a39fc5ac.png)

**Comment by unoebauer** [comment] 2017-10-06 14:38
According to @yeganer, this issue has been fixed by #778. Closing this one.

**Comment by livnehra** [comment] 2017-10-10 19:57
Hi,

NLTE is not working again...
It worked well when I was on version dev2869, except the atomic database was bad for some elements.
Now I rebased to dev3025, and NLTE doesn't work at all.
I'm using the same sample files posted above, with kurucz_cd23_chianti_H_He.h5 from tardis-refdata/atom_data/.

The result:
[result.txt](https://github.com/tardis-sn/tardis/files/1373250/result.txt)

Hope I'm not doing something silly...
[pip_list_new.txt](https://github.com/tardis-sn/tardis/files/1373254/pip_list_new.txt)

Thanks!

**Comment by yeganer** [comment] 2017-10-11 06:53
@livnehra Which setup caused this error? Setup 1 or Setup 2?

**Comment by yeganer** [comment] 2017-10-11 07:16
I think you have to use the other atomic database: `kurucz_atom_chianti_many.h5`. If I read the error correctly, it is looking for collisional data which the default database does not contain. `kurucz_atom_chianti_many.h5` contains these data for S, Si, Ca and Mg.

**Comment by livnehra** [comment] 2017-10-11 10:31
OK,
So with `kurucz_atom_chianti_many.h5` Si II works but S II and Ca II give the same KeyError.
Before the latest updates  (~2 months) S and Ca did work...

**Comment by yeganer** [comment] 2017-10-11 12:23
I checked, `kurucz_atom_chianti_many.h5` only contains ions for Silicon. I'll have a look what went wrong because I'm confident it worked one month ago during GSoC.

**Comment by yeganer** [comment] 2017-10-12 06:30
@livnehra I tracked down the problem to a bug in carsus and will look into a fix. Afterwards the atomic database has to be regenerated which takes several hours. You can expect an update tomorrow or maybe even late this evening (CET).

**Comment by livnehra** [comment] 2017-10-20 08:27
Hi,
Any news regarding this issue?
I'm really looking forward to doing some more Tardis runs :)
Thanks!!

**Comment by wkerzendorf** [comment] 2017-10-20 09:26
@livnehra I'm sure you want to explore the kilonova ;-) @yeganer can you tell me what needs to be fixed or what is fixed. Thank you very much

**Closed** 2017-11-03 15:36 UTC
Labels: atomic, plasma, priority - high

**Comment by wkerzendorf** [comment] 2017-11-03 15:38
@livnehra it should be fixed with the new atomic data that @yeganer just pushed

@yeganer thank you very much for doing this!!!

**Comment by livnehra** [comment] 2017-11-04 21:03
Many thanks !!
Will check ASAP
