### ISSUE TITLE
Installation errors with anaconda2 5.1.0 and latest tardis

### ISSUE THREAD

**Issue by astrobit** [tardis-sn/tardis#810] opened 2018-03-23 22:17 UTC
I am trying to install the latest version of tardis according to the installation instructions at https://tardis.readthedocs.io/en/latest/installation.html.
I have anaconda2 5.1.0 installed (fresh installation), and am using Fedora 24.  I've also tried this using anaconda3 as well as a RHEL 7 system. All anaconda instllations are fresh.

All of them seem to encounter the same problem, when I do the step 
`pip install git+https://github.com/tardis-sn/tardis` 
the installation starts, but encounters and error that seems to be
`TypeError: 'NoneType' object is not callable`
I have confirmed that pip is running from anaconda, not elsewhere (e.g. `which pip` shows the path to anaconda). There are versions of python 2 and python 3 installed on my system outside of anaconda.

I have attached a log of the attempted install with more complete details of the problem.
[tardis-install.log](https://github.com/tardis-sn/tardis/files/1843676/tardis-install.log)

**Comment by wkerzendorf** [comment] 2018-03-29 13:09
@astrobit sorry about the long delay. Not sure what is going on. Can you post the whole traceback. It seems that our continuous integration has also started to flag this issue. @tardis-sn/core any ideas?

**Comment by wkerzendorf** [comment] 2018-03-29 14:01
@astrobit the problem is an outdated cython version - I updated the requirements in #809 - there is still a graphviz problem and I'm in the process of fixing that as well.

**Comment by wkerzendorf** [comment] 2018-04-05 15:03
@astrobit try it now

**Comment by unoebauer** [comment] 2018-07-19 09:30
The cython issues have escalated to a much larger problem. See summary in issue #842.

**Comment by unoebauer** [comment] 2018-07-19 09:31
I am closing this one. The new reference issue for the cython problems is #842.

**Closed by unoebauer** 2018-07-19 09:31 UTC
